wandb_version: 1

dropout:
  value: 0.5
hid_dim:
  value: 32
learning_rate:
  value: 0.015
num_epochs:
  value: 200
num_iterations:
  value: 2
num_runs:
  value: 5
smooth_fac:
  value: 0.8500000000000002
weight_decay:
  value: 0.0005
