wandb_version: 1

dropout:
  desc: null
  value: 0.5
hid_dim:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.002
num_epochs:
  desc: null
  value: 1
num_iterations:
  desc: null
  value: 2
num_runs:
  desc: null
  value: 5
smooth_fac:
  desc: null
  value: 0.7000000000000002
weight_decay:
  desc: null
  value: 0.0002
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1687294865.899809
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.9.17
      5: 0.15.4
      8:
      - 1
      - 5
