wandb_version: 1

dropout:
  value: 0.5
hid_dim:
  value: 16
learning_rate:
  value: 0.0115
num_epochs:
  value: 1
num_iterations:
  value: 3
num_runs:
  value: 5
smooth_fac:
  value: 0.30000000000000004
weight_decay:
  value: 0.0002
