wandb_version: 1

dropout:
  value: 0.5
hid_dim:
  value: 32
learning_rate:
  value: 0.016
num_epochs:
  value: 200
num_iterations:
  value: 3
num_runs:
  value: 5
smooth_fac:
  value: 0.6250000000000001
weight_decay:
  value: 0.0001
