wandb_version: 1

dropout:
  desc: null
  value: 0.5
hid_dim:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.0025
num_epochs:
  desc: null
  value: 200
num_iterations:
  desc: null
  value: 3
num_runs:
  desc: null
  value: 5
smooth_fac:
  desc: null
  value: 0.30000000000000004
weight_decay:
  desc: null
  value: 0.0005
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687297904.476554
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.9.17
      5: 0.15.4
      8:
      - 5
