wandb_version: 1

dropout:
  value: 0.5
hid_dim:
  value: 16
learning_rate:
  value: 0.007000000000000001
num_epochs:
  value: 200
num_iterations:
  value: 2
num_runs:
  value: 5
smooth_fac:
  value: 0.25000000000000006
weight_decay:
  value: 0.0001
